/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2018-12-22 20:18:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.CafeGo.DBConnector;
import com.CafeGo.logincheck;
import javax.swing.JOptionPane;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1545483043432L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.CafeGo.DBConnector");
    _jspx_imports_classes.add("com.CafeGo.logincheck");
    _jspx_imports_classes.add("javax.swing.JOptionPane");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"reponsiveNavigation.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("<center>\r\n");
      out.write("<a href=\"main.jsp\"><img src = \"image/logo.png\" width=\"264px\" height=\"88px\" align=\"center\"></a>\r\n");
      out.write("</center>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"nav_wrapper\"> \r\n");
      out.write("  <nav class=\"menu\">\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li><a href=\"main.jsp\">Home</a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"main.jsp\">홈페이지 소개</a></li>\r\n");
      out.write("          <li><a href=\"main.jsp\">오늘의 카페 추천</a></li>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#Link\">List</a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#Link\">카페 목록</a></li>\r\n");
      out.write("          <li><a href=\"#Link\">카페 분류 »</a>\r\n");
      out.write("          <ul>\r\n");
      out.write("              <li><a href=\"#Link\">별점</a></li>\r\n");
      out.write("              <li><a href=\"#link\">지역</a></li>\r\n");
      out.write("              <li><a href=\"#Link\">테마</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"review.jsp\">Review</a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"review.jsp\">방문 후기 목록</a></li>\r\n");
      out.write("          <li><a href=\"#Link\">방문 후기 작성</a></li>\r\n");
      out.write("          <li><a href=\"#Link\">방문 후기 수정</a></li>\r\n");
      out.write("          <li><a href=\"#Link\">방문 후기 삭제</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("      </li>  \t\t\r\n");
      out.write("  \t\t");

  		String log = (String)session.getAttribute("login");
  		
  		if(log!=null&&log.equals("yes")){
  		// 로그인 상태인 경우 보여지는 메뉴
      
      out.write("\r\n");
      out.write("      <li><a href=\"myPage.jsp\">MyPage</a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"myPage.jsp\">MyPage</a></li>\r\n");
      out.write("          <li><a href=\"logout.jsp\">로그아웃</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      ");
 }
  		else if((String)session.getAttribute("id")==null){
    	  // 로그아웃 상태인 경우 보여지는 메뉴
    	  
      out.write("\r\n");
      out.write("    \t  <li><a href=\"#Link\">Login</a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("          <li><a href=\"find.jsp\">아이디/비밀번호 찾기</a></li>\r\n");
      out.write("          <li><a href=\"signup.jsp\">회원가입</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("    \t  ");
} 
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    <ul>\r\n");
      out.write("      <li><a href=\"search.jsp\">Search</a>\r\n");
      out.write("        <ul>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("  </nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2>Sign Up</h2>\r\n");
      out.write("\t<hr noshade align=\"left\" width=\"120\" size=\"3\">\r\n");
      out.write("\t<small><span style=\"color: red\">*</span> 표시는 필수 입력 사항입니다.</small><br><br>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t<form name=\"fr\" method=\"post\" action=\"infoInsert.jsp\" onsubmit=\"return formcheck()\">\r\n");
      out.write("      <table border=\"0\" width=\"800\">\r\n");
      out.write("      <tr height=\"50\">\r\n");
      out.write("        <td width=\"200\"><img src=\"image/dot.png\" width=\"12\" height=\"12\"> 이름<span style=\"color: red\">*</span></td>\r\n");
      out.write("        <td><input name=\"name\" value=\"\" id=\"name\" placeholder=\"이름\" type=\"text\" /></td>\r\n");
      out.write("        <td></td>\r\n");
      out.write("        <td width=\"200\"><img src=\"image/dot.png\" width=\"12\" height=\"12\"> 생년월일</td>\r\n");
      out.write("        <td><input type=\"date\" id=\"bdate\" name=\"bdate\"></td>\r\n");
      out.write("        <td></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr height=\"50\">\r\n");
      out.write("        <td><img src=\"image/dot.png\" width=\"12\" height=\"12\"> 아이디<span style=\"color: red\">*</span></td>\r\n");
      out.write("        <form><td><input name=\"id\" value=\"\" id=\"id\" placeholder=\"로그인 시 사용\" type=\"text\"/></td>\r\n");
      out.write("        <td><input type=\"submit\" value=\"중복확인\" onclick=\"location.href='checkId.jsp'\"></td></form>\r\n");
      out.write("        <td><img src=\"image/dot.png\" width=\"12\" height=\"12\"> 닉네임<span style=\"color: red\">*</span></td>\r\n");
      out.write("        <form><td><input name=\"nickname\" value=\"\" id=\"nickname\" placeholder=\"후기 작성시 사용\" type=\"text\"/></td>\r\n");
      out.write("        <td><input type=\"submit\" value=\"중복확인\" onclick=\"location.href='checkNickname.jsp'\"></td></form>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr height=\"50\">\r\n");
      out.write("        <td><img src=\"image/dot.png\" width=\"12\" height=\"12\"> 비밀번호<span style=\"color: red\">*</span></td>\r\n");
      out.write("        <td><input name=\"password\" value=\"\" id=\"password\" placeholder=\"비밀번호\" type=\"text\" /></td>\r\n");
      out.write("        <td></td>\r\n");
      out.write("        <td><img src=\"image/dot.png\" width=\"12\" height=\"12\"> 비밀번호 확인<span style=\"color: red\">*</span></td>\r\n");
      out.write("        <td><input name=\"password_c\" value=\"\" id=\"password_c\" placeholder=\"비밀번호 확인\" type=\"text\" /></td>\r\n");
      out.write("        <td></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr height=\"50\">\r\n");
      out.write("        <td><img src=\"image/dot.png\" width=\"12\" height=\"12\"> 이메일<span style=\"color: red\">*</span></td>\r\n");
      out.write("        <td><input name=\"email\" value=\"\" id=\"email\" placeholder=\"이메일\" type=\"text\" /></td>\r\n");
      out.write("        <td></td>\r\n");
      out.write("        <td><img src=\"image/dot.png\" width=\"12\" height=\"12\"> 연락처</td>\r\n");
      out.write("        <td><input name=\"tel\" value=\"\" id=\"tel\" placeholder=\"-포함해서 입력\" type=\"text\"/></td>\r\n");
      out.write("        <td></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <input type=\"submit\" value=\"가입\">\r\n");
      out.write("      <input type=\"button\" value=\"취소\" onclick=\"location.href='main.jsp'\">\r\n");
      out.write("      </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function formcheck() {\r\n");
      out.write("if(fr.name.value == \"\") {\r\n");
      out.write("    alert(\"이름을 입력해주세요.\");\r\n");
      out.write("    fr.name.focus();\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("else if(fr.id.value == \"\") {\r\n");
      out.write("    alert(\"아이디를 입력해주세요.\");\r\n");
      out.write("    fr.id.focus();\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("else if(fr.nickname.value == \"\") {\r\n");
      out.write("    alert(\"닉네임을 입력해주세요.\");\r\n");
      out.write("    fr.nickname.focus();\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("else if(fr.password.value == \"\") {\r\n");
      out.write("    alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("    fr.password.focus();\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("else if(fr.password.value != fr.password_c.value) {\r\n");
      out.write("    alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("    fr.password.focus();\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("else if(fr.email.value == \"\") {\r\n");
      out.write("    alert(\"이메일을 입력해주세요.\");\r\n");
      out.write("    fr.email.focus();\r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
